export const GET_SERVICE_LIST = 'GET_SERVICE_LIST'
export const GET_SERVICE_LIST_SUCCESS = 'GET_SERVICE_LIST_SUCCESS'
export const GET_SERVICE_DETAILS = 'GET_SERVICE_DETAILS'
export const GET_SERVICE_DETAILS_SUCCESS = 'GET_SERVICE_DETAILS_SUCCESS'
export const FETCH_SERVICE_REJECTED = "FETCH_SERVICE_REJECTED";
export const SET_SERVICE_DETAILS_ID = "SET_SERVICE_DETAILS_ID"