export const ITEM_ADD = 'ITEM_ADD'
export const ITEM_EDIT = 'ITEM_EDIT'
export const ITEM_SAVE = 'ITEM_SAVE'
export const CANCEL = 'CANCEL'
export const ITEM_DELETE = 'ITEM_DELETE'
export const CHANGE_TITLE = 'CHANGE_TITLE'
export const CHANGE_PRICE = 'CHANGE_PRICE'
export const FILTER = 'FILTER'